### ISSUE TITLE
Dashboard is not working in Mozilla browser

### ISSUE THREAD

**Issue by ianaya89** [autonomoussoftware/metronome.io#50] opened 2018-06-18 19:27 UTC

**Comment by gabmontes** [comment] 2018-06-18 19:59
Not able to reproduce neither on Firefox for macOS nor Windows.

**Comment by tparvu** [comment] 2018-06-18 20:14
I checked this last night with Firefox on Windows 10 which was fine. 

However, on Linux not so much.

![image](https://user-images.githubusercontent.com/13166222/41559578-0bcb93e2-730a-11e8-950c-74e8ac0eaec0.png)

![image](https://user-images.githubusercontent.com/13166222/41559654-406452c4-730a-11e8-802b-ef54f5dc7061.png)

**Comment by gabmontes** [comment] 2018-06-18 23:00
@tparvu please check if this is not related to some settings on your box.

Unable to reproduce here in Firefox 60.0.2 on Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/2621975/41566518-3384f0e0-7332-11e8-9e09-7edbfdf8c932.png)

**Comment by tparvu** [comment] 2018-06-19 13:11
I can confirm that Firefox works fine on a new stock installation of Ubuntu Bionic Beaver Desktop.

Probably a fonts package issue. Since other users have reported this, I'll see if I can't track down the needed fonts.

**Comment by gabmontes** [comment] 2018-06-19 20:05
@tparvu ok. Closing now as it looks specific to some installation but not a general problem.

Let us know if you find something we should fix/update.

**Closed by gabmontes** 2018-06-19 20:05 UTC
Labels: bug
